// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'quote_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_QuoteModel _$$_QuoteModelFromJson(Map<String, dynamic> json) =>
    _$_QuoteModel(
      author: json['author'] as String,
      text: json['text'] as String,
      quoteCategory: $enumDecode(_$QuoteCategoryEnumMap, json['quoteCategory']),
    );

Map<String, dynamic> _$$_QuoteModelToJson(_$_QuoteModel instance) =>
    <String, dynamic>{
      'author': instance.author,
      'text': instance.text,
      'quoteCategory': _$QuoteCategoryEnumMap[instance.quoteCategory]!,
    };

const _$QuoteCategoryEnumMap = {
  QuoteCategory.age: 'age',
  QuoteCategory.alone: 'alone',
  QuoteCategory.amazing: 'amazing',
  QuoteCategory.anger: 'anger',
  QuoteCategory.anniversary: 'anniversary',
  QuoteCategory.architecture: 'architecture',
  QuoteCategory.art: 'art',
  QuoteCategory.attitude: 'attitude',
  QuoteCategory.beauty: 'beauty',
  QuoteCategory.best: 'best',
  QuoteCategory.birthday: 'birthday',
  QuoteCategory.business: 'business',
  QuoteCategory.car: 'car',
  QuoteCategory.change: 'change',
  QuoteCategory.christmas: 'christmas',
  QuoteCategory.communication: 'communication',
  QuoteCategory.computers: 'computers',
  QuoteCategory.cool: 'cool',
  QuoteCategory.courage: 'courage',
  QuoteCategory.dad: 'dad',
  QuoteCategory.dating: 'dating',
  QuoteCategory.death: 'death',
  QuoteCategory.design: 'design',
  QuoteCategory.diet: 'diet',
  QuoteCategory.dreams: 'dreams',
  QuoteCategory.easter: 'easter',
  QuoteCategory.education: 'education',
  QuoteCategory.environmental: 'environmental',
  QuoteCategory.equality: 'equality',
  QuoteCategory.experience: 'experience',
  QuoteCategory.failure: 'failure',
  QuoteCategory.faith: 'faith',
  QuoteCategory.family: 'family',
  QuoteCategory.famous: 'famous',
  QuoteCategory.fathersday: 'fathersday',
  QuoteCategory.fear: 'fear',
  QuoteCategory.finance: 'finance',
  QuoteCategory.fitness: 'fitness',
  QuoteCategory.food: 'food',
  QuoteCategory.forgiveness: 'forgiveness',
  QuoteCategory.freedom: 'freedom',
  QuoteCategory.friendship: 'friendship',
  QuoteCategory.funny: 'funny',
  QuoteCategory.future: 'future',
  QuoteCategory.gardening: 'gardening',
  QuoteCategory.god: 'god',
  QuoteCategory.good: 'good',
  QuoteCategory.government: 'government',
  QuoteCategory.graduation: 'graduation',
  QuoteCategory.great: 'great',
  QuoteCategory.happiness: 'happiness',
  QuoteCategory.health: 'health',
  QuoteCategory.history: 'history',
  QuoteCategory.home: 'home',
  QuoteCategory.hope: 'hope',
  QuoteCategory.humor: 'humor',
  QuoteCategory.imagination: 'imagination',
  QuoteCategory.inspirational: 'inspirational',
  QuoteCategory.intelligence: 'intelligence',
  QuoteCategory.jealousy: 'jealousy',
  QuoteCategory.knowledge: 'knowledge',
  QuoteCategory.leadership: 'leadership',
  QuoteCategory.learning: 'learning',
  QuoteCategory.legal: 'legal',
  QuoteCategory.life: 'life',
  QuoteCategory.love: 'love',
  QuoteCategory.marriage: 'marriage',
  QuoteCategory.medical: 'medical',
  QuoteCategory.memorialday: 'memorialday',
  QuoteCategory.men: 'men',
  QuoteCategory.mom: 'mom',
  QuoteCategory.money: 'money',
  QuoteCategory.morning: 'morning',
  QuoteCategory.mothersday: 'mothersday',
  QuoteCategory.motivational: 'motivational',
  QuoteCategory.movies: 'movies',
  QuoteCategory.movingon: 'movingon',
  QuoteCategory.music: 'music',
  QuoteCategory.nature: 'nature',
  QuoteCategory.newyears: 'newyears',
  QuoteCategory.parenting: 'parenting',
  QuoteCategory.patience: 'patience',
  QuoteCategory.patriotism: 'patriotism',
  QuoteCategory.peace: 'peace',
  QuoteCategory.pet: 'pet',
  QuoteCategory.poetry: 'poetry',
  QuoteCategory.politics: 'politics',
  QuoteCategory.positive: 'positive',
  QuoteCategory.power: 'power',
  QuoteCategory.relationship: 'relationship',
  QuoteCategory.religion: 'religion',
  QuoteCategory.respect: 'respect',
  QuoteCategory.romantic: 'romantic',
  QuoteCategory.sad: 'sad',
  QuoteCategory.saintpatricksday: 'saintpatricksday',
  QuoteCategory.science: 'science',
  QuoteCategory.smile: 'smile',
  QuoteCategory.society: 'society',
  QuoteCategory.sports: 'sports',
  QuoteCategory.strength: 'strength',
  QuoteCategory.success: 'success',
  QuoteCategory.sympathy: 'sympathy',
  QuoteCategory.teacher: 'teacher',
  QuoteCategory.technology: 'technology',
  QuoteCategory.teen: 'teen',
  QuoteCategory.thankful: 'thankful',
  QuoteCategory.thanksgiving: 'thanksgiving',
  QuoteCategory.time: 'time',
  QuoteCategory.travel: 'travel',
  QuoteCategory.trust: 'trust',
  QuoteCategory.truth: 'truth',
  QuoteCategory.valentinesday: 'valentinesday',
  QuoteCategory.war: 'war',
  QuoteCategory.wedding: 'wedding',
  QuoteCategory.wisdom: 'wisdom',
  QuoteCategory.women: 'women',
  QuoteCategory.work: 'work',
};
